name: Build and Run Backend & Frontend

on: [push, pull_request]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Build Backend (Flask)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Backend Dependencies
        run: |
          cd flask-server
          pip install -r requirements.txt

      - name: Run Flask Server
        run: |
          cd flask-server
          python app.py &
        continue-on-error: true