name: Build and Run Backend & Frontend

on:
    push:
        branches:
            - master

jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Build Backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install Backend Dependencies
        run: |
          cd flask-server
          pip install -r requirements.txt

      - name: Run Server Script
        run: |
            cd flask-server
            python -m py_compile server.py
            python -c 'import server'

  build-frontend:
    runs-on: ubuntu-latest
    name: Build Frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'

      - name: Install Frontend Dependencies
        run: |
          cd frontend-v1
          npm install

      - name: Build Frontend
        run: |
          cd frontend-v1
          npm run build
