name: Build and Run Backend

on: [push, pull_request]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Build Backend (Flask)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install Backend Dependencies
        run: |
          cd flask-server
          pip install -r requirements.txt

      - name: Lint and Run Server Script
        run: |
            cd flask-server
            python -m py_compile server.py
            python -c 'import server'